---
global_become: true

configure_dotfiles: true
install_docker: true

dotfiles_repo: https://github.com/steffkelsey/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/steffkelsey/dotfiles
dotfiles_files:
  - .aliases.bash
  - .aliases.docker
  - .bash_prompt
  - .gitconfig
  - .gitignore
  - .gitmessage
  - .git_prompt
  - .ideavimrc
  - .inputrc
  - .tmux.conf

packages:
  - firewalld
  - podman
  - tmux
  - compat-lua-libs # start neovim requirements
  - libtermkey
  - gcc
  - make
  - libtree-sitter
  - libvterm
  - luajit
  - luajit2.1-luv
  - msgpack
  - unibilium
  - xsel # end neovim requirements
  - ripgrep # for grep searching with Telescope

packages_state: present

git_protocol_port: 9418/tcp
