---
configure_dotfiles: true
install_docker: true

dotfiles_repo: https://github.com/steffkelsey/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/steffkelsey/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .gitmessage
  - .ideavimrc
  - .inputrc
