---
configure_dotfiles: true
install_docker: true

dotfiles_repo: https://github.com/steffkelsey/dotfiles.git
dotfiles_repo_ssh: git@github.com:steffkelsey/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/steffkelsey/dotfiles
dotfiles_files:
  - .aliases.bash
  - .aliases.docker
  - .bash_prompt
  - .gitconfig
  - .gitignore
  - .gitmessage
  - .git_prompt
  - .ideavimrc
  - .inputrc
  - .tmux.conf
  - .config/nvim/lua/chadrc.lua
  - .config/nvim/lua/mappings.lua
  - .config/nvim/lua/options.lua
  - .config/nvim/lua/plugins/init.lua

packages:
  - firewalld
  - podman
  - tmux
  - unzip
  - zip
  - hplip # start printer setup fixes
  - nss-mdns # end printer setup fixes
  - compat-lua-libs # start neovim requirements
  - libtermkey
  - gcc
  - make
  - libtree-sitter
  - libvterm
  - luajit
  - luajit2.1-luv
  - msgpack
  - unibilium
  - xsel # end neovim requirements
  - ripgrep # for grep searching with Telescope

packages_state: present

git_protocol_port: 9418/tcp
cups_protocol_port: 631/tcp

nvchad_starter_useless_files:
  - LICENSE
  - README.md
  - .git
