- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/install_go.yml
    - include: tasks/node_tools.yml
    - include: tasks/hashicorp.yml
    - include: tasks/cron.yml

