---
- name: Configure Linux dev machine
  hosts: all
  become: true

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
    - role: geerlingguy.docker
      when: install_docker
 
  tasks:
    - name: linux-dev | Install packages
      include_tasks: tasks/packages.yml

    - name: linux-dev | Connect dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: linux-dev | Configure firewall
      include_tasks: tasks/ports.yml

    - name: linux-dev | Configure tmux plugin manager
      include_tasks: tasks/tpm.yml

    - name: linux-dev | Configure vim-plug manager
      include_tasks: tasks/vimplug.yml
