---
- name: Configure Linux dev machine
  hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
    - role: geerlingguy.docker
      when: install_docker
 
  tasks:
    - name: linux-dev | Install packages
      include_tasks: tasks/packages.yml

    - name: linux-dev | Connect dotfiles
      include_tasks: tasks/dotfiles.yml
