---
- name: Configure Linux dev machine
  hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
    - role: geerlingguy.docker
      when: install_docker
 
  #tasks:

        #- name: linux-dev | Maybe install docker
        #  include_role:
        #    name: geerlingguy.docker
        #  when: install_docker
