---
- name: Configure Linux dev machine
  hosts: all
  become: "{{ lookup('ansible.builtin.env', 'GLOBAL_BECOME', default='true') }}"

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: linux-dev | Configure NvChad Starter
      include_tasks: tasks/nvchad.yml
  
  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
    - role: geerlingguy.docker
      when: install_docker
 
  tasks:
    - name: linux-dev | Install packages
      include_tasks: tasks/packages.yml

    - name: linux-dev | Install mise
      include_tasks: tasks/mise.yml

    - name: linux-dev | Connect dotfiles
      include_tasks: tasks/dotfiles.yml

    - name: linux-dev | Configure firewall
      include_tasks: tasks/ports.yml

    - name: linux-dev | Configure tmux plugin manager
      include_tasks: tasks/tpm.yml

    - name: linux-dev | Configure neovim
      include_tasks: tasks/neovim.yml
