---
- name: linux-dev | Edit .bashrc to load the dotfiles
  become: false
  ansible.builtin.blockinfile:
    path: '~/.bashrc'
    marker: "# {mark} ALIASES AND PROMPT"
    block: |
      # import the aliases
      . ~/.aliases.bash
      # set the custom prompt
      . ~/.bash_prompt

- name: linux-dev | Edit .bashrc for shell before
  become: false
  ansible.builtin.blockinfile:
    path: '~/.bashrc'
    insertbefore: BOF
    marker: "# {mark} SHELL BEFORE"
    block: |
      # Allow local customizations in the ~/.shell_local_before file
      if [ -f ~/.shell_local_before ]; then
        . ~/.shell_local_before
      fi 

- name: linux-dev | Edit .bashrc for shell after
  become: false
  ansible.builtin.blockinfile:
    path: '~/.bashrc'
    insertafter: EOF
    marker: "# {mark} SHELL AFTER"
    block: |
      # Allow local customizations in the ~/.shell_local_after file
      if [ -f ~/.shell_local_after ]; then
        . ~/.shell_local_after
      fi 

- name: linux-dev | Maybe change remote url to ssh
  become: false
  community.general.git_config:
    scope: local
    repo: "{{ dotfiles_repo_local_destination }}"
    name: remote.origin.url
    value: "{{ dotfiles_repo_ssh }}"
  vars:
    block_this: "{{ lookup('ansible.builtin.env', 'BLOCK_REMOTE_SET_URL_SSH', default='false') }}"
  when: 
    - dotfiles_repo_ssh
    - not block_this
