- name: Create install directory
  file:
    path: /usr/local/hashicorp
    state: directory
    mode: '0755'

- name: Install Packer
  unarchive:
    src: "https://releases.hashicorp.com/packer/{{ version }}/packer_{{ version }}_{{ os }}_amd64.zip"
    dest: /usr/local/hashicorp
    remote_src: yes
  vars:
    version: 1.10.0
    os: "{{ ansible_facts['system']|lower }}"

- name: Install Terraform
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_{{ os }}_amd64.zip"
    dest: /usr/local/hashicorp
    remote_src: yes
  vars:
    version: 1.7.1
    os: "{{ ansible_facts['system']|lower }}"

- name: Install Nomad
  unarchive:
    src: "https://releases.hashicorp.com/nomad/{{ version }}/nomad_{{ version }}_{{ os }}_amd64.zip"
    dest: /usr/local/hashicorp
    remote_src: yes
  vars:
    version: 1.7.6
    os: "{{ ansible_facts['system']|lower }}"

- name: Install Consul
  unarchive:
    src: "https://releases.hashicorp.com/consul/{{ version }}/consul_{{ version }}_{{ os }}_amd64.zip"
    dest: /usr/local/hashicorp
    remote_src: yes
  vars:
    version: 1.18.1
    os: "{{ ansible_facts['system']|lower }}"
