- name: Create install directory
  file:
    path: /usr/local/hashicorp
    state: directory
    mode: '0755'

- name: Install Packer
  unarchive:
    src: "https://releases.hashicorp.com/packer/{{ version }}/packer_{{ version }}_{{ os }}_amd64.zip"
    dest: /usr/local/hashicorp
    remote_src: yes
  vars:
    version: 1.6.1
    os: "{{ ansible_facts['system']|lower }}"

- name: Install Terraform
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_{{ os }}_amd64.zip"
    dest: /usr/local/hashicorp
    remote_src: yes
  vars:
    version: 0.13.0
    os: "{{ ansible_facts['system']|lower }}"

- name: Install Vagrant
  apt:
    deb: "https://releases.hashicorp.com/vagrant/{{ version }}/vagrant_{{ version }}_x86_64.deb"
  vars:
    version: 2.2.9
