---
- name: linux-dev | Add mise repo
  get_url:
    url: 'https://mise.jdx.dev/rpm/mise.repo'
    dest: '/etc/yum.repos.d/mise.repo'
    owner: root
    group: root
    mode: 0644

- name: linux-dev | Install mise package
  ansible.builtin.package:
    name: mise
    state: present

- name: linux-dev | Edit .bashrc for mise activation
  become: false
  ansible.builtin.blockinfile:
    path: '~/.bashrc'
    marker: '# {mark} MISE ACTIVATION (ANSIBLE)'
    block: |
      eval "$(/usr/bin/mise activate bash)"
