- name: linux-dev | Create ~/.config/share directory
  become: false
  ansible.builtin.file:
    path: '~/.config/share'
    state: directory
    mode: "0755"

- name: linux-dev | Download neovim tar.gz and unarchive to ~/.config/share
  become: false
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz"
    dest: '~/.config/share'
    remote_src: true

- name: linux-dev | Make sure ~/.local/bin exists
  become: false
  ansible.builtin.file:
    path: '~/.local/bin'
    state: directory
    mode: "0755"

- name: linux-dev | Link neovim to ~/.local/bin
  become: false
  ansible.builtin.file:
    state: link
    src: '~/.config/share/nvim-linux-x86_64/bin/nvim'
    dest: '~/.local/bin/nvim'
