- name: Prep for NVM
  file:
    path: $HOME/.nvm
    state: directory
  become: yes

- name: Install NVM
  git:
    repo: "https://steffkelsey:{{ lookup('env', 'OAUTH_TOKEN') }}@github.com/nvm-sh/nvm.git"
    dest: $HOME/.nvm/
    version: v0.35.3
  become: yes

- name: Install Latest Node
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install v14.16
    nvm use 14.16
    exit 0

