- name: Prep for NVM
  file:
    path: /usr/local/nvm
    state: directory
    mode: '0755'

- name: Install NVM
  git:
    repo: "https://steffkelsey:{{ lookup('env', 'OAUTH_TOKEN') }}@github.com/nvm-sh/nvm.git"
    dest: /usr/local/nvm/
    version: v0.38.0
  become: yes


- name: Install Latest Node
  shell: |
    export NVM_DIR=/usr/local/nvm
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install v14.17.6
    nvm use 14.17.6
    exit 0

