- name: linux-dev | Check if ~/.config/nvim exists
  become: false
  ansible.builtin.stat:
    path: '~/.config/nvim'
  register: config_nvim

- name: linux-dev | Maybe create ~/.config/nvim directory
  become: false
  ansible.builtin.file:
    path: '~/.config/nvim'
    state: directory
    mode: "0755"
  when: not config_nvim.stat.exists

- name: linux-dev | Maybe clone NvChad/starter
  become: false
  ansible.builtin.git:
    repo: "https://github.com/NvChad/starter"
    dest: '~/.config/nvim'
    single_branch: yes
    depth: 1
  when: not config_nvim.stat.exists

# Remove the README, LICENSE files and .git directory
- name: linux-dev | Maybe remove NvChad/starter useless files
  become: false
  ansible.builtin.file:
    path: "~/.config/nvim/{{ item }}"
    state: absent
  when: not config_nvim.stat.exists
  with_items: "{{ nvchad_starter_useless_files }}"
