---
- name: linux-dev | Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: "{{ packages_state }}"

#- name: linux-dev | Install python packages
#  pip:
#    executable: pip3
#    name:
#      - thefuck
