- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - zsh
      - python3-dev
      - python3-pip
      - python3-setuptools
      - tmux
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - jq
      - software-properties-common
      - vim
      - unzip
      - zip
      - graphviz

- name: Add Docker official gpg key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }} {{ ansible_facts['distribution_release']|lower }} stable

- name: Index new repos into the cache
  apt: update_cache=yes
  changed_when: False

- name: Install docker ce packages
  apt:
    name: "{{ docker_packages }}"
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install python packages
  pip:
    executable: pip3
    name:
      - thefuck
      - awscli

- name: Install docker-compose
  pip:
    executable: pip3
    name: docker-compose
  become: yes

- name: Install sandboxd
  unarchive:
    src: " https://github.com/benvan/sandboxd/archive/master.zip"
    dest: /usr/local
    remote_src: yes

