---
- name: linux-laptop | Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - zsh
      - python3-dev
      - python3-pip
      - python3-setuptools
      - tmux
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - jq
      - software-properties-common
      - vim
      - unzip
      - zip
      - graphviz

- name: linux-laptop | Install python packages
  pip:
    executable: pip3
    name:
      - thefuck
