- name: Install packages
  apt: "{{ packages }}"
  vars:
    packages:
      - git
      - zsh
      - python3-dev
      - python3-pip
      - python3-setuptools
      - tmux

- name: Add Docker official gpg key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Index new repo into the cache
  become: yes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install docker ce packages
  apt:
    name: "{{ docker_packages }}"
    force_apt_get: yes
  vars:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install python packages
  pip:
    executable: pip3
    name:
      - thefuck

- name: Install docker-compose
  pip:
    executable: pip3
    name: docker-compose
    extra_args: --user

