---
- name: linux-dev | Start and enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes

- name: linux-dev | Open tcp port for git protocol
  ansible.posix.firewalld:
    port: "{{ git_protocol_port }}"
    permanent: true
    state: enabled

- name: linux-dev | Open tcp port for CUPS print server
  ansible.posix.firewalld:
    port: "{{ cups_protocol_port }}"
    permanent: true
    state: enabled
