---
- name: linux-dev | Clone tpm to $HOME/.tmux/plugins/tpm
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: '{{ ansible_env.HOME }}/.tmux/plugins/tpm'
    single_branch: yes
