---
- name: linux-dev | Clone tpm to ~/.tmux/plugins/tpm
  become: false
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: '~/.tmux/plugins/tpm'
    single_branch: yes
    depth: 1
