---
- name: linux-dev | Create ~/.vim/autoload directory
  become: false
  ansible.builtin.file:
    path: '~/.vim/autoload'
    state: directory
    mode: "0755"

- name: linux-dev | Download vim-plug/plug.vim file to ~/.vim/autoload/plug.vim
  become: false
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: '~/.vim/autoload/plug.vim'
    mode: "0644"
