---
# tasks file for awscliv2

- name: "awscliv2 | Run uninstall if the clean var has been set to true"
  include_tasks: uninstall.yml
  when: awscliv2_clean

- name: >
    Run task that gathers information for gathering info about current
    install state
  include_tasks: setup.yml

# We only want to run this when the cli is not installed or when the installed
# version does not match the target version.
- name: "awscliv2 | Run task that installs aws cli v2"
  include_tasks: install.yml
  when: >
    not aws_link.stat.exists or
    awscliv2_current_version is not defined or
    awscliv2_current_version != awscliv2_version
