---
# tasks file for go_dev

- name: "go_dev | Run task that gathers system information"
  include_tasks: setup.yml

- name: "go_dev | Run task that installs go"
  include_tasks: install.yml
  # yamllint disable-line rule:line-length
  when: >
    not go_binary.stat.exists or
    current_go_version is not defined or
    current_go_version.stdout|default('') not in
    expected_go_version_output|string
