---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-rockylinux9-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host    
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    GLOBAL_BECOME: false
    BLOCK_REMOTE_SET_URL_SSH: true
