---
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
    - name: Verify docker binary is available
      command: docker version
      register: docker_version_result
      changed_when: false
      failed_when: docker_version_result.rc != 0
