---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        go_root: "/usr/local/go"
        go_version: 1.17.6
        go_temporary_dir: /tmp
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
