---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: true

  tasks:
  - name: Include the same setup tasks
    include_tasks: ../../tasks/setup.yml

  # The go_root has to be set in the group_vars in the inventory in the
  # molecule.yml file
  - name: Gather go version output
    command: "{{ go_root }}/bin/go version"
    register: go_version_output
    changed_when: false

  - name: Verify go version
    assert:
      that: go_version_string in go_version_output.stdout
