---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Load the scenario variables
    include_vars: vars/main.yml

  - name: Include the same setup tasks
    include_tasks: ../../tasks/setup.yml

  - name: Gather aws version output
    command: "aws --version"
    register: aws_version_output
    changed_when: false

  - name: Pull the version string out of the output
    set_fact:
      # yamllint disable-line rule:line-length
      aws_version_to_verify: "{{ aws_version_output.stdout | regex_search(awscliv2_version_regex_search_string, '\\1') | first }}"

  - name: Assert that the installed version matches the target
    assert:
      that: awscliv2_version == aws_version_to_verify
