return {
  {
    "christoomey/vim-tmux-navigator",
    lazy = false,
  },
  {
    "stevearc/conform.nvim",
    opts = require "configs.conform",
  },
  {
    "neovim/nvim-lspconfig",
    lazy = false,
    config = function()
      require "configs.lspconfig"
    end,
  },
  {
    "mason-org/mason-lspconfig.nvim",
    lazy = false,
    dependencies = {
      "mason-org/mason.nvim",
      "neovim/nvim-lspconfig",
    },
    opts = {},
  },
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    lazy = false,
    dependencies = { "mason-org/mason.nvim" },
    opts = {}, -- set in .config/nvim/lua/configs/lsp.lua
  },
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "cmake",
        "css",
        "cuda",
        "dockerfile",
        "gitattributes",
        "gitcommit",
        "git_config",
        "gitignore",
        "git_rebase",
        "go",
        "hcl",
        "helm",
        "html",
        "http",
        "javascript",
        "jinja_inline",
        "jinja",
        "jq",
        "jsdoc",
        "jsonnet",
        "json",
        "luadoc",
        "lua",
        "make",
        "mermaid",
        "nginx",
        "ninja",
        "pem",
        "printf",
        "properties",
        "proto",
        "python",
        "regex",
        "rust",
        "scss",
        "sql",
        "ssh_config",
        "starlark",
        "terraform",
        "toml",
        "vimdoc",
        "vim",
        "xml",
        "yaml",
        "zig"
      },
    },
  },
}
