---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - converge
    - verify
    - destroy
