---
- name: Converge
  hosts: all
  tasks:

    - name: Load scenario variables
      include_vars: vars/main.yml

    - name: "Run the role installing an old version"
      include_role:
        name: "awscliv2"
      vars:
        awscliv2_version: "{{ older_awscliv2_version }}"
