---
# defaults file for awscliv2

# find versions at https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst
awscliv2_version: 2.4.16
# setting clean to true will uninstall any existing old installs
awscliv2_clean: false
# if you're already updating the apt-cache in another place and hate seeing it
# again you can skip it! (set to false by default)
awscliv2_apt_cache_update: false
